# This workflow will update github pages when a release is created

name: update-github-pages

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  update-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install ğŸ”§
        run: yarn install

      - name: build â›ï¸
        run: npm run build:docs

      - name: commit ğŸ–Šï¸
        run: |
          git config --global user.email "zomixi@qq.com"
          git config --global user.name "zomixi"
          git add -A docs
          git commit -m "chore: update docs" --no-verify

      - name: push ğŸš€
        run: git push
